### ISSUE TITLE
Vivo 50

### ISSUE THREAD

**Issue by linshumeng** [Yaqi-Zheng/beihuagong#3]
Can you receive the email and Vivo 50? 😊

**Comment by linshumeng** [comment]
You can close the issue here.

![image](https://user-images.githubusercontent.com/54089164/207160503-d31ed116-4c58-4279-95ec-0d42ff89694d.png)

**Comment by linshumeng** [comment]
You can close the issue here.
![image](https://user-images.githubusercontent.com/54089164/207160779-562e1af7-9e02-4446-ab71-88831efb1479.png)

**Comment by linshumeng** [comment]
You can close the issue here.

![image](https://user-images.githubusercontent.com/54089164/207160924-24c92820-ffa2-4252-a118-a6d3ec9d8837.png)

**Comment by Yaqi-Zheng** [comment]
磙
